name: Auto Update README

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 20 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
          python-version: '3.x'
          architecture: 'x64'
    - name: Run assemble.py
      run: |
         python assemble.py
    - name: Commits
      run: |
        git config --local user.email "tony9402@naver.com"
        git config --local user.name "Auto BOT"
        git add status.md
        git commit -m "Auto UPDATE"
    - name: Push
      uses: ad-m/github-push-action@master
      with:
         branch: 'main'
         github_token: $
