name: Auto Judge

on:
  issue_comment:
    types: [ created ]

jobs:
  build:
    if: contains(github.event.comment.body, 'judge') 
    runs-on: ubuntu-latest
    env:
      filepath: "${{ github.event.comment.body }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: refs/pull/${{ github.event.issue.number }}/merge
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Setup pip
        run: |
          python -m pip install --upgrade pip
          pip install bs4 requests
      - name: Run judge
        run: |
          python scripts/judge.py "${{env.filepath}}" > result.out
      - name: Save result
        run: |
          cat result.out
          echo "RESULT=`head -1 result.out`" >> $GITHUB_ENV
          tail -5 result.out > result2.out
      - name: comment
        uses: actions/github-script@0.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { issue: { number: issue_number }, repo: { owner, repo }  } = context;
            const { RESULT } = process.env
            if (RESULT === "ERROR") {
              github.issues.createComment({ issue_number, owner, repo, body: 'ERROR' });
              github.issues.addLabels({ issue_number, owner, repo, labels: [ "Simple Check Failed" ] })
            }
            else {
              const fs = require('fs');
              var text = fs.readFileSync('result2.out', 'utf8');
              github.issues.createComment({ issue_number, owner, repo, body: text });
              github.issues.addLabels({ issue_number, owner, repo, labels: [ "Simple Check Success" ] })
            }

