name: Auto Judge

on:
  issue_comment:
    types: [created]

jobs:
  build:
    if: contains(github.event.comment.body, 'judge')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Setup pip
        run: |
          python -m pip install --upgrade pip
          pip install bs4 requests
      - name: Run judge
        run: |
          python scripts/judge.py > result.out
      - name: Save result
        run: |
          cat result.out
          echo `head -1 result.out` >> $GITHUB_ENV
          echo set -n '2,\$p' result.out` >> $GITHUB_ENV
      - name: comment
        uses: actions/github-script@0.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { issue: { number: issue_number }, repo: { owner, repo }  } = context;
            const { result, result_message }= process.env
            if (result === "ERROR")
            github.issues.createComment({ issue_number, owner, repo, body: 'ERROR' });
            else 
            github.issues.createComment({ issue_number, owner, repo, body: `${result_message}` });


