name: Auto Update README

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
          python-version: '3.x'
          architecture: 'x64'
    - name: Setup pip
      run: |
        python -m pip install --upgrade pip
        pip install pytz
    - name: Config Github
      run: |
        git config --local user.name "auto bot"
    - name: Run assemble.py
      run: |
         python assemble.py --push
    - name: Commits
      run: |
        git add .
        git commit -m "Solution UPDATE"
    - name: Push
      uses: ad-m/github-push-action@master
      with:
         branch: 'main'
         github_token: $
